const express = require('express');
const bodyParser= require('body-parser');

const globalAlignment = require('./alignment/global');
const localAlignment = require('./alignment/local');
const db = require('./mongo-connection/db');
const db_leaderboard = require('./mongo-connection/db-leaderboard');
const user = require('./mongo-connection/user');

var app = express();

app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});

app.use(bodyParser.urlencoded({extended: true}));
app.use(bodyParser.json());

//GET requests for development 
app.get('/', function (req, res) {
  res.sendFile(__dirname + '/dummyHTML/index.html');
});

app.get('/signup', function (req, res) {
  res.sendFile(__dirname + '/dummyHTML/signup.html');
});

app.get('/login', function (req, res) {
  res.sendFile(__dirname + '/dummyHTML/login.html');
});

//User requests
app.post('/signup', user.createUsers);
app.post('/login', user.login);
app.get('/seeResults', user.seeResults);
//Leaderboard
app.post('/add', user.addToLeaderBoard);
app.get('/leaderboard', user.leaderBoard);


//Alignment requests
app.post('/global', (req, res) => {
	var result = globalAlignment.getGlobalAlignment(req.body.query, req.body.database, req.body.gap);
	return res.json(result);
});

app.post('/local', (req, res) => {
	var result = localAlignment.getLocalAlignment(req.body.query, req.body.database, req.body.gap);
	return res.json(result);
});

app.listen(4200, function () {
  console.log('Protein alignment tutor listening on port 3000!');
});

/*
localAlignment.getLocalAlignment(`gcctcatttttcccggctcctatttaagatggagttgctctggttcacacacctctgaca
tgatcattgcccactgcggcttccacctcccgggttcaagagatcctcctgcctcaccct
cccaaggtgctgggactacaggtgtgtgccaccagctcagctaatttttgtattttttgt
agagatggtgtttttccatgttgcccaggctggtctcaaactcctgggctcaagcaatcc
ttctgtctcagcctcccaaagtactgggattacaggcatgtcccaccatgcccagactaa
tatttacttttaatcagactaagatagggttactacttgagttgctatggctccagctga
aagaaagcccgtgcagtcatatcacgcgtaaacatttgctttatgctaaaaatatggtgg
acctggcattacagctattacaaatctcctaagatgtctcgggtagtgtattagttactt
ttcatactgctatgaagaaatactggaaactgggtaatttataaagaaaaagaggtttaa
tgtactcacagttccacaaggctggagaggcctcagaatcatggtggaaggcaaagaagg
agcaaaaaggtatgtcttccatggcagcaggcaagagagcacgtgcagggaaactgccct
ttataaaaccatcagatttagtgagatgtattcactatcacgagaacagtatgggaaaaa
cctgcccccatgattcgattacctcctaccgggtccctcccacgacacatggggattatg
ggaactacaattcaagatgaaatttgggtggggacgcagccaaaccatatcgggtagcaa
caacctagggtcagttttgcaggtggtaaagccatttaccaagatagttgtaggtaaaga
agggcagatttattagagaaattgtgaaaatatgttgcagtgggcagctcagcagagaag
gggctacctgcaaagaggcaagggctggaggaaagttttatagggtcctgctgaagggtg
ctacgtgtggaatgaggtcattgtgcccgcaggttgtttgtgattagctgtctctaacaa
ttgttcatacaataattgttcattattgttctcaacttggggctctccccaacctgggga
cccttccttattgttgcttacttatcaggtctccacataaaggtgtggaaacttcattca
ttcatatcttcaacacaaattgtaggtagcctgttttttaaaacatttattcaacaaata
tttagtccaagccactattacttactaccttctctactattgtatggacttttaactatc
tctgacactattcactattcttccacattctctattatttatacctatggtaaaatttgc
cagtttgaccatacaactaatactcacagggaatatatagagtctagaagaaaatataca
ggtccttaaaggctgccctgccaacaaaaccataacgcaggaacaaacatcacaactatg
ccaaataatcaatcctacaatgtccaaaattttactttaaaactggaattaccagacttc
ctttctgcattaaccagtttaactagacagtaacgaaatattcctactttatgctgtgat
agtttgtttgtttgtttgtttgtttatttatttatttatttaagacagagtttcgctctt
gttgcccaggctggagtgcagtggcacgatctcagctcaccacaacctccgcctcccagg
ttcaagcgattctcctgcctcagcctcccgagtagctgggattacaggcatgtaccacca
cgcccgggtaattttgtatttttagtagagacggggggtttctccatgttggtcaggctg
gtctagaactccagacctcaggtgatacccctgcctcagcctcccaatgtgctgggatta
cagctgtgaagccaccgcgcccggctgctgtgatagttgagatgtaaaccaaaaataaaa
ttctaagccacccagtccgactgaatggacccttcctgttgagcaaggacattccaaagt
aaactgaaaagaccagcttaggccatgatgggaaggggaggtgtcaacatgcctcattct
accttcctccctctggaatccagacacaactgaccagcattaacattaaaacagagatct
taagctgggcacagtggctcatgcctataatcccagcactttgggaggccaaggtgggat
cacctgaggtcagaagttcaagaccagcctggccagtatggtgaagccatgtctctacta
aaaatacaaaattagccggacattgtggtgcacgtctgtcatcccagcaaggcaggcgaa
tcacttgaacccaggaagcagaggttgcagtgagccaggatcatgccattgcactccagc
ctggtcaacagagcgagactccgcctcattaaaaaaaaaaaaaaaaaaaaaaa`, `caggacttctggatggatctgggagcctgccccttgggatttggcaaaacttcccatctc
cttagctacctgtccttaatcttatccctgacccctcgagggctttcaagatagcctctg
ttaacatcactaccctctgcctgtgtagaactttatagaaaggctaggcaaaaaatgaga
cccagagatatggaagaaactggccaaagaggggaaagtgggctatttcttttttttttt
tcttttttttttctgagacagagtctcaccctgttgcccaggctggagtgcagtgacagc
gatcttggctcactgcaagctccgcctcccgggttcacgccattcttctgcctcagcctc
ctgagcagctatgactacaggtgcccaccaccatgcctggctaatttttttatattttta
ttagagacagggtttcaccatgttagccaggttggtcttgatctcctgaccttgtgatcc
gcccgccttggcctcccaaagtgctgggattacaggccaccgtacccggccaggctattt
ttttgttttgtttttgtttactactgtattgcttttctctttttcatatttattgagcac
ctactatatgccagtcaccatgctagatgctttagtaacatgaaggtttcaaactaagaa
aagctcaacaaagagccctttagaaaggtaacagttttcctgtgtattgggggagtgggt
ctcataaggttgtatgatgagaagcgcaagtaattgttttgttttttttttgagacaatg
tcttgctctgtcgatcaggctggagtgcagtggcgtcatctcagctcgctacaacctcca
cctcctgggtttaagtgattctctggcctcagcctcctgagtagctgagattacaggcac
gcgccaccacgcccggctaatttttgtatttttagtagagacagggtttcactatgttgg
tcaggctgatcttgaactcccggcctcaggtgatctgcctgccttggcctcccaaactgc
tgggattacaggcatgagccaccacgcccagcctggctaaggttcattatccccatcttt
cagatgaggaggcacacaactctccccagatcccacgtcacagagaatgcaggtctgagt
ctgttccttgagctcagggtcttggcaatggtgatgctttggagctgcagaatcctctgt
tggggatggggctgccctgtgcattatagtacgtttagcaacatccctagcttccaccta
ctaaatgccactagcactccttcagatgagaccaccaaaaatgtctccagatgttaccac
atgtcccctggggggtaaaagtgcccccgttgagagcactggctcttttcttcacagtcc
tgacctggtggcctgcacaggccacttctccgaagtgtttcaatgcactctctgccctgg
gtaccttggacacagcaccctggcccagagaggttggctgacttgcctgagacgctgctt
cctgggagacgcagtagcatctttcctttctgttctggttatctttcttagttctttacc
accttatattccccatgacaggtgtgtttatgtacacacatctgcctcactccactcagc
tccctgtcaggtttcctgccagtctgtccctcttccttcaggctcagctacgtcctgcac
agacagtaccactgcacatacctgtgtgtgcccagcggtggacccacctccaaaagcagc
cagtgctgacagcagagagccttccacactcaagtcaggccaagcaggaatcgctacctg
cctgtcatgaccacattctcagtgaacattgacaaagcccccttagcagctaattagccc
tgccgtgcgctagggatgcaatttctcatctggcagtgcgccacactcctgcctccctgc
ccaaaggacgtagtggctgctgctgatcgtctgcactgctgttccaggggcaggaggttt
gctgcaaatcaggtacccccagctcagtgagcagaaccagtccaaggttgagtgaggaga
agggcaagaagggcaggcacagccgtgagtatgttctggggctaagtaaccatgagatca
gcccagagaccttgcacagttaggcaggcctggacttctcgcccttccccttgcagcttc
tgctctcccagctagggactgaggaaagccctgcttctagatgccatgtgctgctgcctg
gcacgataggtacccatctgtccttggggttcctgagcctggagagcgggctttgtgagc
actggtgcctcacctgcctggctcagctctgcagccacaatatatgcttaatacctattt
gttaaatgattgaagacttgactgccattcagtacagagaattagccaggtgaataaaca
ggatgtgtcatagaggttctagaattgatcatgaccctttctgtctcattcctgacttct
aataccgtatatgccaaatggggttctgctgtgatttaatttcttaaggactgggtttat
caaaagtccctcctgatctaatcctttcctctaggaaggcttctcctttcttcatctgtc
ctaagtgcatggtcttcatctcctgggtggtccagactaggtggcactgggcctgcaggc
ctctagctgctcaaggatggccctgtctgcatgcttcctttcaaaagctagcatagaaag
gagggcccaaggtgaggaaatttgtccaaagtcacccaatgagtcgcaggaagggctaga
atctggttatctggaccgtcctagagcactttcacagtgacagccggctggaatcaagtt
ttcatttagaaaaatggctagaagttagggcattgcctgcagccactgaaaagcagcttt
aggagcagatgtccacgtaatagaaggagatgggctagggcctgccacggaagccagcaa
gcgcgtgggagctgggggaggaaaggagcaaaaggcaagaacaggcagtatgtccgcggt
gcccacagtgctgtgggtacaagcaaggggaaaagagcccatggtgtgcagaaaaccatg
cgtcatgattcttatttcctgctcgcagctttgactctctgcctcatctcttcctggaag
tgtcttggaagttaggcgactgcacagggaaaggttcgctgcagtgcttgcaggcctgca
cccatttattcatccggtggatatttgctgggtgcccggcctggggatccatggtgagcg
aggaaggcatggtattgaagtggtatgcctgcatgaccttggcgggggcgcatggcatag
agaggacaggcttcagaacaggcaggcaagggctgaaatcctatctctgccaccgaacag
ctaatgaccccagcaagcaatttcacatccccgaactttcctgtttcctcatgtgtcaaa
tggggatgatctcgagacgactctccagagtaaccacgtgaagcacctagcacaggggct
gacgcaaacagctgggcatcggaggagcctccagggttgtgacctccagtggcttatttt
ccttttgggatcttctctcctagatcctcccctttaattccctgtgaaatttaccacttt
catattgaatcgttggcacacagggctaactgcttgttcacctgaaggaagctacagagt
tcaggtttcttttttctttctttctttcttttttgcttttttaagatgatcttgctccgt
cacccaggctggagtgcagtggcgtaatcatggcttcctgcagcctcaaactcctgggct
caatgagttccttgagatcttccatcctcagcttcccaagtagctagtagtagtagtggc
ttgcaccaacgctcctgccctaattttcaatatttttttgtagagataggatctcactgt
gttacccaagctagacttgaactcctggcctcaagcgatccttccgccttggcctcccaa
agtgttgggattacaggcattagctaccacacctggccaaggcccaggtttcgacagaaa
gggagagaaaacctgccagagatgccatttcggagccactctgcttggcagggacctgtg
ttcccctcatgcaggttcatccttagagggctgcggtcttatctggttgtgcaaaagtcc
cacaacctttctggattgatagtttgtggtgaaataaacaattttagtttgtttggagaa
tcttttgtatacaaaatacaaataaaacctaaatcaaagaaacaga`, -3);


globalAlignment.getGlobalAlignment(`atacgttgtttcactattccaagttccaagtaaccatggtgaatatggtttccccattcc
aagtaaccattgtgaatgtggttatacacctccacctgggtgacagagcaagactctgtc
tctaaataaataagtaaattcagtttggaccaatgaagaaggtaatatgtaaatatggaa
tattgggaaaaattgaccacgttatttggagttaatgttaaggaatcaaaggaaacattg
aactaattggacttagactcatctctgctatgactatcattctactttagatccctaatg
ccaggcaaatagtccctccttattaagaataaatgtactggctgggcatggtggttcata
cttataatcccagcactttgggaggctgaactgggaggatcacctgaggccaggagtttg
agactagccctggcaacatagcaagaccctgtctctacaaaaaaatttttaaaaaattag
ctgggtatggggtatgcacctatagtcccagctactcaaagactgaagcgagaggatcac
ttgagcccaggagttcaaggctgcagtgagctatgattgcactaccgcacaccagcctgg
gtgagggggtgagacctggactcaaggg`,
`tatctttgatctcttgcctctttatcttccaaacctaaaatgtttaccacctggcccttt
acagaaaaatatttgccagtccctgctgtagaaggttatatagccagcagctttcaaagt
aaccttttacctggaaatgtgaattctctcttagttctggtcatctgttatttgtgggag
ccaatcctctctctgttggctgatgatgagaattctgttatataccacaacacaaacttg
gggataaaactttccattaggcatttctgtaaaatttccatctattttagaagcagaact
aaggtgaagcccagtgtgaatgaatcctgcttgttggtacaagccaagtgggacatttgg
cagcaaagcccaggagtccttggtgctcttcttttaactgcctcctcatctcattgggct
gcccggtgttaactggttgattatcacctctgtgttttgcctgcaaggaaagaagctact
gacacccagagtggctcagcgatactcacacgtgctttcagttactttcgcagcatttgg
ttaaagtgagtttagctgcacatcctcacttggtaacattctgtggctgtgaaaattgtt
tctctctt`, -3);
*/
